version: '3.1'

services:
  app:
    build: .
    container_name: recruitwise_app
    ports:
      - '127.0.0.1:8080:8080'
    environment:
      - DB_USER=developer
      - DB_URL=jdbc:postgresql://db:5432/recruit_db
      - DB_PASSWORD=DeveloperRoot
    depends_on:
      - db
  db:
    image: "postgres"
    container_name: db
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=DeveloperRoot