version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/recruit_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=PostgresRoot
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: 'postgres:13'
    environment:
      - POSTGRES_DB=recruit_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=PostgresRoot
    ports:
      - "5432:5432"
